---
- name: db_setup | Creating DB
  mysql_db:
    name: "{{ mysql_dynamic_inventory_db_name }}"
    state: present
  become: true

- name: db_setup | Creating DB User
  mysql_user:
    host: "{{ item }}"
    name: "{{ mysql_dynamic_inventory_user }}"
    password: "{{ mysql_dynamic_inventory_password }}"
    priv: "{{ mysql_dynamic_inventory_db_name + '.*:ALL' }}"
    state: present
  become: true
  loop:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - "::1"
    - localhost
    - "%"

- name: db_setup | Checking If Schema Has Been Imported
  command: >
    mysql -u {{ mysql_dynamic_inventory_user }}
    --password={{ mysql_dynamic_inventory_password }}
    -e "show tables from {{ mysql_dynamic_inventory_db_name }}"
  register: _dynamic_inventory_schema
  changed_when: false

- name: db_setup | Generating Schema
  template:
    src: schema.sql.j2
    dest: /tmp/schema.sql
    mode: u=rw,g=r,o=r
  when: _dynamic_inventory_schema['stdout_lines'] == []

- name: db_setup | Importing Schema
  mysql_db:
    name: "{{ mysql_dynamic_inventory_db_name }}"
    state: import
    target: /tmp/schema.sql
  become: true
  when: _dynamic_inventory_schema['stdout_lines'] == []
